# Run on main: plus_<x> with groups: main crashes with ValueError at benchmarks.py:122 (int('<x>'))
[global]
runtime=1
monitor=none
engine=sleep
stressor_range=auto

[a]
selected_cpus=numa0 numa1
selected_cpus_scaling=plus_<x>
