# Run on main: explicit quadrant on a CPU-less node: main fails cleanly with 'Quadrant 1 does not exists'
[global]
runtime=1
monitor=none
engine=sleep
stressor_range=auto

[e]
selected_cpus=quadrant0 quadrant1
selected_cpus_scaling=iterate
