# This configuration will :
# - load all cores with a matrixprod test during 15 sec.
[global]
runtime=15
monitor=all

[randread_cmdline]
engine=fio
engine_module=cmdline
engine_module_parameter_base="--filename=/dev/sdp --direct=1 --rw=randread --bs=4k --ioengine=libaio --iodepth=256 --numjobs=4 --time_based --group_reporting --readonly"
hosting_cpu_cores=all
hosting_cpu_cores_scaling=none
stressor_range=auto

