[global]
runtime=120
monitor=all
engine=stressng
selected_cpus=simple
selected_cpus_scaling=iterate
stressor_range=auto
skip_method=wait

[wait]
# Let's make a sleep run to see the idle behavior
engine=sleep
selected_cpus=1
selected_cpus_scaling=none
stressor_range=1

[avx]
engine_module=vnni
engine_module_parameter=noavx_vpaddb,avx_vpaddb512

[cpu]
engine_module=cpu
engine_module_parameter=int128,float128,fft,int128decimal128,matrixprod

[stream]
engine_module=stream

[memrate]
engine_module=memrate

[qsort]
engine_module=qsort

