[global]
runtime=60
monitor=all
engine=stressng
engine_module=cpu
engine_module_parameter=int64
stressor_range=auto

[numa_domains]
selected_cpus=numa0 numa1
selected_cpus_scaling=iterate

[threads]
selected_cpus=core0-1

[idle]
engine=sleep
engine_module=sleep
engine_module_parameter=sleep
stressor_range=1
