[global]
runtime=1
monitor=none
engine=sleep
stressor_range=auto

[each_core]
selected_cpus=each-core

[each_numa]
selected_cpus=each-numa

[each_quadrant]
selected_cpus=each-quadrant

[each_numa_plus_1]
selected_cpus=each-numa
selected_cpus_scaling=plus_1

[each_core_curve]
selected_cpus=each-core
selected_cpus_scaling=curve
