[global]
runtime=60
monitor=all

[spike_all]
engine=spike
engine_module=cpu
engine_module_parameter_base=high:10 low:5
stressor_range=auto
selected_cpus=all
selected_cpus_scaling=none

[spike_quadrant]
engine=spike
engine_module=cpu
engine_module_parameter_base=high:10 low:5
stressor_range=auto
selected_cpus=QUADRANT0 QUADRANT1 all
selected_cpus_scaling=iterate

[spike_auto]
engine=spike
engine_module=cpu
engine_module_parameter_base=auto:10
stressor_range=auto
selected_cpus=all
selected_cpus_scaling=none
sync_start=time