[global]
runtime=1
monitor=none
engine=sleep
engine_module=sleep
engine_module_parameter=sleep

[plus_1]
stressor_range=8,1,4

[plus_2]
stressor_range=1-8
stressor_range_scaling=plus_2

[curve]
stressor_range=1-64
stressor_range_scaling=curve

[cpus_and_stressors]
selected_cpus=each-numa
selected_cpus_scaling=plus_2
stressor_range=1,2,4,8
stressor_range_scaling=plus_2
